name: Deploy Walrus Site

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy site to Walrus
        uses: MystenLabs/walrus-sites/.github/actions/deploy@main
        with:
          SUI_ADDRESS: ${{ vars.SUI_ADDRESS }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE }}
          DIST: ./public
          EPOCHS: 5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
